set encoding=utf-8
set nocompatible
syntax enable
"set background=dark
colorscheme solarized

filetype off

""""""""""""" Vundle stuff
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'kien/ctrlp.vim'
Plugin 'rizzatti/dash.vim'
Plugin 'uarun/vim-protobuf'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-fireplace'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'vim-scripts/paredit.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'fatih/vim-go'
Plugin 'godlygeek/tabular'
Plugin 'bling/vim-airline'
Plugin 'itspriddle/vim-marked'
Plugin 'tpope/vim-fugitive'
Plugin 'rust-lang/rust.vim'
call vundle#end()
""""""""""""" End Vundle stuff
filetype plugin indent on "required for vundle

set expandtab
set tabstop=2
set softtabstop=2 " tab size when inserting/pasting
set shiftwidth=2 " number of spaces to use for autoindenting
set shiftround
set smarttab
"set autoindent
"set foldenable "fold by default
"set foldmethod=indent
set ruler
set nu
set noerrorbells
set hlsearch
set nowrap
set mouse=a

"clojure options.
" let g:slime_target = "tmux"

" Rainbow parens stuff
au Syntax clojure RainbowParenthesesLoadRound
au Syntax clojure RainbowParenthesesLoadSquare
au Syntax clojure RainbowParenthesesLoadBraces
au BufEnter *.clj RainbowParenthesesToggle
au BufLeave *.clj RainbowParenthesesToggle

let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0

" NERDTree stuff
autocmd vimenter * NERDTree
autocmd VimEnter * wincmd w
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Airline stuff
" TODO make this prettier in iTerm...
"let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'
let g:airline_symbols.branch = '⭠'
let g:airline_symbols.readonly = '⭤'
let g:airline_symbols.linenr = '⭡'

let g:airline_theme='badwolf'
"let g:airline_enable_branch     = 1
"let g:airline_enable_syntastic  = 1

" force .md files to showup as markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
