# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="norm"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rails ruby lein cabal)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=/usr/local/Cellar/protobuf241/2.4.1/bin:/usr/local/bin:$HOME/bin:$HOME/Scripts:$HOME/.cabal/bin:$PATH:$HOME/.rvm/bin
export ANT_OPTS="-Xmx2048m -Xms512m"
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export GOPATH=$HOME/Code/Go
export CORE=$HOME/Code/Code42/core
export EDGE_CASE=$HOME/Code/Code42/edge_case
export TERM=xterm-256color #(make sure this is right on OSX)

# stop annoying beep
unsetopt beep

# color ls output
case `uname` in
  Darwin)
    eval "$(gdircolors ~/.dir_colors)"
    alias "ls=gls --color=auto --group-directories-first"
    alias "core=cd ~/code/Code42/core"
    ;;
  Linux)
    eval "$(dircolors ~/.dir_colors)"
    alias "ls=ls --color=auto --group-directories-first"
    alias "emacs=emacs -nw"
    ;;
esac

#This is to force tab completion to use gls and $LS_COLOR
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"

#colored man pages (not sure how much I like this)
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

source ~/.profile
source $HOME/.aliases

# this fixes something and I don't remember what...
eval "`npm completion`"

canILeaveYet() {
  TIME_TO_LEAVE='5:00PM'
  TIME_TILL_FIVE=$(( $(date -d $TIME_TO_LEAVE +%s) - $(date +%s) ))
  EIGHT_HOURS=28800000
  if [ $TIME_TILL_FIVE -gt $EIGHT_HOURS ]
    then
      echo "You are here way to early!"
  elif [ $TIME_TILL_FIVE -lt "0" ]
    then
      echo "You should be gone already!"
  else
      echo $(date -u -d @$TIME_TILL_FIVE +'%Hh %Mm %Ss till 5:00PM')
  fi
  if [ $(date +%G) -eq "2015" ]
    then
      echo "It's still 2015 :("
  fi
}
eval "$(rbenv init -)"
